config/routes.rb
Rails.application.routes.draw do

  resources :achievements

  get 'admin', to: 'admin#index'

  controller :sessions do
    get  'login', to: :new
    post 'login', to: :create
    delete 'logout', to: :destroy
  end

  get 'statistics/index', to: 'statistics#index'

  get 'statistics/teams', to: 'statistics#teams'

  get 'statistics/teams/:id', to: 'statistics#show_team'

  get 'statistics/players', to: 'statistics#players'

  get 'statistics/players/:id', to: 'statistics#show_player'
  
  get 'scoreboard', to: 'statistics#score_board'
  
  get 'scoreboard/:id', to: 'statistics#player_score_board'

  resources :rounds

  resources :matches do
      put 'create_event'
  end

  resources :teams

  resources :players do
    post 'achievement_check'
  end
  
  post 'achievement_check_all', to: 'statistics#achievement_check_all'

  root to: 'statistics#index', as: 'statistics'

end

app/views/admin/index.html.erb
<h1>Admin page</h1><br>

<%= link_to 'Index', statistics_path, class: 'button success radius expand'  %> <br>

<%= link_to 'Create round', new_round_path, class: 'button success radius expand'  %> <br>

<%= link_to 'Players', players_path, class: 'button success radius expand'   %> <br>

<%= link_to 'Teams', teams_path, class: 'button success radius expand'  %>  <br>

<%= link_to 'Register player', new_player_path, class: 'button success radius expand' %><br>

<%= link_to 'Register team', new_team_path, class: 'button success radius expand'  %> <br>

<%= link_to "Update Achievements for all players", achievement_check_all_path, method: :post, data: {confirm: "Detta tar lång tid att exekvera, säker på att du vill fortsätta?"}, class: 'button success radius expand' %>

<%= link_to 'Logout', logout_path, method: :delete, class: 'button alert radius expand' %>