config/routes.rb
Rails.application.routes.draw do

  resources :achievements

  get 'admin', to: 'admin#index'

  controller :sessions do
    get  'login', to: :new
    post 'login', to: :create
    delete 'logout', to: :destroy
  end

  get 'statistics/index', to: 'statistics#index'

  get 'statistics/teams', to: 'statistics#teams'

  get 'statistics/teams/:id', to: 'statistics#show_team'

  get 'statistics/players', to: 'statistics#players'

  get 'statistics/players/:id', to: 'statistics#show_player'
  
  get 'scoreboard', to: 'statistics#score_board'
  
  get 'scoreboard/:id', to: 'statistics#player_score_board'

  resources :rounds

  resources :matches do
      put 'create_event'
  end

  resources :teams

  resources :players do
    post 'achievement_check'
  end
  
  post 'achievement_check_all', to: 'statistics#achievement_check_all'

  root to: 'statistics#index', as: 'statistics'

end

app/models/match.rb
class Match < ActiveRecord::Base
  has_many :games
  has_many :teams, :through => :games
  has_many :participants
  has_many :rounds, :through => :participants
  has_many :events

  validates :home, :away, presence: true

  def wins(team)
      if teams[0] == team
        if home > away
          @wins = 1
        else
          @wins = 0
        end
      else
        if away > home
          @wins = 1
        else
          @wins = 0
        end
      end
  end

  def losses(team)
      if teams[0] == team
        if home >= away
          @losses = 0
        else
          @losses = 1
        end
      else
        if away >= home
          @losses = 0
        else
          @losses = 1
        end
      end
  end

  def ties(team)
    if home == away
      @ties = 1
    else
      @ties = 0
    end
  end

  def goals_for(team)
    if teams[0] == team
      @goals_for = home
    else
      @goals_for = away
    end
  end

  def goals_against(team)
    if teams[0] == team
      @goals_against = away
    else
      @goal_against = home
    end
  end

  def goal_difference(team)
      if teams[0] == team
        @goal_difference = home - away
      else
        @goal_difference = away - home
      end
  end

  def highscore_goals_for(team)
    if teams[0] == team
      @highscore_goals_for = home
    else
      @highscore_goals_for = away
    end
  end

  def last_gameday
    
  end


end

app/models/round.rb
class Round < ActiveRecord::Base
  serialize :schedule, Array
  has_many :participants
  has_many :players, :through => :participants, :dependent => :destroy
  has_many :matches, :through => :participants
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :set_round, only: [:show, :edit, :update, :destroy]

  # GET /rounds
  # GET /rounds.json
  def index
    @match = Match.new
    @rounds = Round.all
  end


  # GET /rounds/1
  # GET /rounds/1.json
  def show
    @match = Match.new
    @round = Round.find(params[:id])
    @schedule = @round.schedule
    @players = @round.players
    @pre_round = @round.created_at - 16.hours
    @after_round = @round.created_at + 16.hours
    @last_time_players_ajax = []
    @players.each do |player|
      if player.statistic_last_times.any?
        player.statistic_last_times.each do |statistic|
          # matching statistic created in time between of pre_round and after_round
          if ((statistic.created_at > @pre_round) && (statistic.created_at < @after_round)) 
            @last_time_players_ajax.push({"player" => player, "player_stats" => player.statistic_last_times.last, "player_balance" => player.statistic_last_times.last.balance})
          end
        end
      end
    end
    @last_time_players_sorted_ajax = @last_time_players_ajax.sort_by { |k| k["player_balance"] }.reverse
  end

  # GET /rounds/new
  def new
    @round = Round.new
  end

  # GET /rounds/1/edit
  def edit
  end

  # POST /rounds
  # POST /rounds.json
  def create
    @round = Round.new(round_params)
    @player_array = []
    @round.players.each do |player|
      @player_array.push(player.id)
    end
    @schedule = @player_array.shuffle
    @round.schedule = get_schedule(@schedule)
    respond_to do |format|
      if @round.save
        format.html { redirect_to @round, notice: '' }
        format.json { render :show, status: :created, location: @round }
      else
        format.html { render :new }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rounds/1
  # PATCH/PUT /rounds/1.json
  def update
    respond_to do |format|
      if @round.update(round_params)
        format.html { redirect_to @round, notice: 'Round was successfully updated.' }
        format.json { render :show, status: :ok, location: @round }
      else
        format.html { render :edit }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rounds/1
  # DELETE /rounds/1.json
  def destroy
    @round.destroy

    respond_to do |format|
      format.html { redirect_to new_round_path, notice: 'Round was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_round
      @round = Round.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def round_params
      params.require(:round).permit(:name, player_ids: [], team_ids: [])
    end
end

app/helpers/rounds_helper.rb
module RoundsHelper

  def winodds(teamone, teamtwo)
    @player1 = Player.find_by(name: teamone[0])
    @player2 = Player.find_by(name: teamone[1])
    @player3 = Player.find_by(name: teamtwo[0])
    @player4 = Player.find_by(name: teamtwo[1])
    
    @players = [@player1, @player2, @player3, @player4]
    # for holding players with win/lose ratio
    @win_lose_ratios = []
    
    @players.each do |player|
      if player.statistic_all_times.last != nil
        # check if they have atleast one win and one lose
        if player.statistic_all_times.last.wins > 0 && player.statistic_all_times.last.losses > 0
          @wins = player.statistic_all_times.last.wins.to_f
          @losses = player.statistic_all_times.last.losses.to_f
          @win_lose_ratio = (@wins / @losses)
          # push players win/lose ratio
          @win_lose_ratios.push(@win_lose_ratio)
        end
      end
    end
    # check for nil values
    if @win_lose_ratios.length == 4
      # getting teams ratio instead of players ratio
      @team_one_ratio = (@win_lose_ratios[0] + @win_lose_ratios[1]) / 2
      @team_two_ratio = (@win_lose_ratios[2] + @win_lose_ratios[3]) / 2
      # divide team ratio with total ratio to get team win odds and multiply by 100 to get percentage
      @winodds_team_one = (@team_one_ratio / (@team_one_ratio + @team_two_ratio)) * 100
      @winodds_team_two = (@team_two_ratio / (@team_one_ratio + @team_two_ratio)) * 100
      @winodds_array = [@winodds_team_one.round(3).to_s + "% to Win", @winodds_team_two.round(3).to_s + "% to Win"]
    end
    return @winodds_array
  end
  
end

app/views/rounds/_form.html.erb
<%= form_for(@round) do |f| %>
  <% if @round.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@round.errors.count, "error") %> prohibited this round from being saved:</h2>

      <ul>
      <% @round.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.collection_select :player_ids, players, :id, :name, {}, { multiple: true, 'style' => 'height:200px' } %>
    </div>

  <div class="actions">
    <%= f.submit class: 'button expand' %>
  </div>
<% end %>

app/views/rounds/_test.html.erb
<%= form_for(@match, remote: true) do |f| %>
    <% if @match.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

          <ul>
            <% @match.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
	<div class="speechinput">
	</div>
	<br>
    <div class="field">
		<% @home_players = home_players %>
		<% @away_players = away_players %>
		<% @winodds_array = winodds(@home_players, @away_players)%>
		<% if @winodds_array == nil %>
			<% @winodds_array = ["TBA", "TBA"]%>
		<% end %>
  	  <div id="home_players">
  	  	<%= @home_players[0] + " " + @home_players[1]%>
      </div>
	  <div id="home_team">
      	<%= f.label home %>
      </div>
      <%= f.hidden_field :team_ids, :value => @team_one, :multiple => true %> <%= random_team %><br> <%= @winodds_array[0] %><br>
      <%= f.number_field :home %><br>
	  
    </div>
    <div class="field">
      <div id="away_players">
      	<%= @away_players[0] + " " + @away_players[1]%>
      </div>
	  <div id="away_team">
      	<%= f.label away %>
      </div>
      <%= f.hidden_field :team_ids, :value => @team_two, :multiple => true %> <%= random_team %><br> <%= @winodds_array[1] %><br>
      <%= f.number_field :away %>
	  <div id="checkdiv">
      2x <%= f.check_box(:bet,:value=>1) %>
  </div>
    </div>
    <div class="actions">
      <%= f.submit class: 'button expand' %>
    </div>
<% end %>

app/views/rounds/edit.html.erb
<h1>Editing round</h1>

<%= render 'form' %>

<%= link_to 'Show', @round %> |
<%= link_to 'Back', rounds_path %>

app/views/rounds/index.html.erb
<h1>Match</h1>

app/views/rounds/new.html.erb
<h1>New round</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_url, class: 'button success radius expand'%>

app/views/rounds/show.html.erb
<h1>Match</h1>
<div id="events">
	<%= render partial: "matches/events" %>
</div>
<div class="matches" id="matches">
	<!-- only display matches for rounds created 12 hours ago -->
<% if @round.created_at > Time.now - 16.hours %>
	<% @schedule.each do |match| %>
 

	    <% @player_one = Player.find(match[0]).teams %>
	    <% @player_two = Player.find(match[1]).teams %>
	    <% @player_three = Player.find(match[2]).teams %>
	    <% @player_four = Player.find(match[3]).teams %>

	    <% @players = [@player_one, @player_two, @player_three, @player_four] %>

	    <% @players[0].each do |team0|
	      @team0 = team0
	      @players[1].each do |team1|
	        @team1 = team1
	        if @team0 == @team1
	          @team_one = @team0.id
	        end
	      end
	    end %>

	   <% @players[2].each do |team0|
	     @team0 = team0
	     @players[3].each do |team1|
	       @team1 = team1
	       if @team0 == @team1
	         @team_two = @team0.id
	       end
	     end
	   end %>
		<div class="match">
	    	<%= render 'test' %><br>
		</div>

	<% end %>
<% end %>
</div>
<div id="scoreboard">
	<%= render partial: 'statistics/score_board'%>
</div>
<%= link_to 'New Round', new_round_path, class: 'button success radius expand' %>