config/routes.rb
Rails.application.routes.draw do

  resources :achievements

  get 'admin', to: 'admin#index'

  controller :sessions do
    get  'login', to: :new
    post 'login', to: :create
    delete 'logout', to: :destroy
  end

  get 'statistics/index', to: 'statistics#index'

  get 'statistics/teams', to: 'statistics#teams'

  get 'statistics/teams/:id', to: 'statistics#show_team'

  get 'statistics/players', to: 'statistics#players'

  get 'statistics/players/:id', to: 'statistics#show_player'
  
  get 'scoreboard', to: 'statistics#score_board'
  
  get 'scoreboard/:id', to: 'statistics#player_score_board'

  resources :rounds

  resources :matches do
      put 'create_event'
  end

  resources :teams

  resources :players do
    post 'achievement_check'
  end
  
  post 'achievement_check_all', to: 'statistics#achievement_check_all'

  root to: 'statistics#index', as: 'statistics'

end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :connections
  has_many :teams, :through => :connections
  has_many :participants
  has_many :rounds, :through => :participants
  has_many :achievements
  has_many :statistic_all_times
  has_many :statistic_last_times
  has_many :statistic_last_seasons
  

  validates :name, uniqueness: true
  has_secure_password



  def streak
    @streak = []
    @win_streak = []
    @lose_streak = []
    @draw_streak = []
    @player_games = []
    teams.each do |team|
      team.matches.each do |match|
        @player_games.push(match)
      end
    end
    @sorted_player_games = @player_games.sort_by &:created_at
    @sorted_player_games.each do |m|
      @teamhome = false
      if m.home != m.away
        self.teams.each do |t|
            if m.teams[0] == t
              @teamhome = true
            end
            end
            if @teamhome
              if m.home > m.away
              @win_streak.push(1)
              @lose_streak = []
              @draw_streak = []
              else
                @win_streak = []
                @lose_streak.push(1)
                @draw_streak = []
              end
            else
              if m.away > m.home
                @win_streak.push(1)
                @lose_streak = []
                @draw_streak = []
              else
                @win_streak = []
                @lose_streak.push(1)
                @draw_streak = []
              end
            end
            else
            @draw_streak.push(1)
            @lose_streak = []
            @win_streak = []
        end
      end
    if @win_streak.length > @lose_streak.length + @draw_streak.length
      @streak.push("Won", @win_streak.inject(:+))
    else
      if @lose_streak.length > @win_streak.length + @draw_streak.length
        @streak.push("Lost", @lose_streak.inject(:+))
      else
        @streak.push("Tied", @draw_streak.inject(:+))
      end
    end
    return @streak
  end


  def award(achievement)
    achievements << achievement.new
  end



  def matches
    @matches = []
    self.teams.each do |t|
       t.matches.each do |m|
         @matches.push(m)
      end
    end
    return @matches
  end

  def sorted_matches
    @player_games = []
    teams.each do |team|
      team.matches.each do |match|
        @player_games.push(match)
      end
    end
    @sorted_player_games = @player_games.sort_by &:created_at
  end

  def goals_scored_record
    @goals_scored = [0]
    self.matches.each do |m|
      @teamhome = false
        self.teams.each do |t|
          if m.teams[0] == t
            @teamhome = true
          end
          end
          if @teamhome
             @goals_scored.push(m.home)
          else
            @goals_scored.push(m.away)
          end
    end
    return @goals_scored.max
  end

  def streak_record
      @win_streak = [0]
      @win_streak_record = [0]
      @player_games = []
      teams.each do |team|
        team.matches.each do |match|
          @player_games.push(match)
        end
      end
      @sorted_player_games = @player_games.sort_by &:created_at
      @sorted_player_games.each do |m|
        @teamhome = false
        if m.home != m.away
          self.teams.each do |t|
            if m.teams[0] == t
              @teamhome = true
            end
          end
          if @teamhome
            if m.home > m.away
              @win_streak.push(1)
            else
              @win_streak_record.push(@win_streak.length)
              @win_streak = [0]
            end
          else
            if m.away > m.home
              @win_streak.push(1)
            else
              @win_streak_record.push(@win_streak.length)
              @win_streak = [0]
            end
          end
        else
          @win_streak_record.push(@win_streak.length)
          @win_streak = [0]
        end
      end
      return @win_streak_record.max
    end

  def clean_sheet_record
    @clean_sheet_streak = [0]
    @clean_sheet_streak_record = [0]
    @player_games = []
    teams.each do |team|
      team.matches.each do |match|
        @player_games.push(match)
      end
    end
    @sorted_player_games = @player_games.sort_by &:created_at
    @sorted_player_games.each do |m|
      @teamhome = false
        self.teams.each do |t|
          if m.teams[0] == t
            @teamhome = true
          end
        end
        if @teamhome
          if m.away == 0
            @clean_sheet_streak.push(1)
          else
            @clean_sheet_streak_record.push(@clean_sheet_streak.length)
            @clean_sheet_streak = [0]
          end
        else
          if m.home == 0
            @clean_sheet_streak.push(1)
          else
            @clean_sheet_streak_record.push(@clean_sheet_streak.length)
            @clean_sheet_streak = [0]
          end
        end
    end
    return @clean_sheet_streak_record.max
  end

  def score_in_five_games
    @score = [0]
    @score_record = [0]
    @player_games = []
    teams.each do |team|
      team.matches.each do |match|
        @player_games.push(match)
      end
    end
    @sorted_player_games = @player_games.sort_by &:created_at
    @sorted_player_games.each do |m|
      if @score.count == 5
        @score.shift
      end
      @teamhome = false
      self.teams.each do |t|
        if m.teams[0] == t
          @teamhome = true
        end
      end
      if @teamhome
        @score.push(m.home)
        else
          @score.push(m.away)
      end
      @score_record.push(@score.inject(:+))
    end
    return @score_record.max
    end

  def score_streak
    @score = [0]
    @score_record = [0]
    @player_games = []
    teams.each do |team|
      team.matches.each do |match|
        @player_games.push(match)
      end
    end
    @sorted_player_games = @player_games.sort_by &:created_at
    @sorted_player_games.each do |m|
      if @score.count == 11
        @score.shift
      end
      @teamhome = false
      self.teams.each do |t|
        if m.teams[0] == t
          @teamhome = true
        end
      end
      if @teamhome
        if m.home > 0
          @score.push(1)
        else
          @score_record.push(@score.inject(:+))
          @score = [0]
        end
      else
        if m.away > 0
        @score.push(1)
        else
          @score_record.push(@score.inject(:+))
          @score = [0]
        end
      end
    end
    return @score_record.max
  end


  def balance_over_500
    @goal_difference = [0]
    @player_games = []
    @balance = []
    @return = false
    teams.each do |team|
      team.matches.each do |match|
        @player_games.push(match)
      end
    end
    @sorted_player_games = @player_games.sort_by &:created_at
    @sorted_player_games.each do |m|
      @teamhome = false
      self.teams.each do |t|
        if m.teams[0] == t
          @teamhome = true
        end
      end
      if @teamhome
         @goals = m.home - m.away
      else
        @goals = m.away - m.home
      end
      if @goals != 0
        if @goals > 0
          @cash = 1
          if @goals > 2
            @cash = @goals.fdiv(2).round(0)
          else
          end
        else
          @cash = -1
          if @goals < -2
            @cash = @goals / 2
          else
          end
        end
      else
        @cash = 0
      end
      if m.bet == 1
        if @cash > 0
          @cash += 1
        end
        if @cash < 0
          @cash -= 1
        end
      end
      @balance.push(@cash)
      if @balance.inject(:+) * 20 > 500
        @return = true
      end
    end
    return @return
  end

  def win_against_record
    @players_won_against = [0]
    @player_games = []
    self.matches.each do |m|
      @teamhome = false
      teams.each do |t|
        if m.teams[0] == t
          @teamhome = true
        end
      end
      if @teamhome
        if m.home - m.away > 4
          @players_won_against.push(m.teams[1].players.first.name, m.teams[1].players.last.name)
        end
      else
       if m.away - m.home > 4
         @players_won_against.push(m.teams[0].players.first.name, m.teams[1].players.last.name)
       end
      end
    end
    return @players_won_against.uniq.length
  end

  def huge_double_win
    @player_games = []
    @huge_win = false
    self.matches.each do |m|
      @teamhome = false
      teams.each do |t|
        if m.bet == 1
          if m.teams[0] == t
            @teamhome = true
          end
          if @teamhome
            if m.home - m.away > 4
              @huge_win = true
            end
          else
            if m.away - m.home > 4
              @huge_win = true
            end
          end
      end
      end
    end
    return @huge_win
  end


  def double_games_record
    @double_games_record = [0]
    self.matches.each do |m|
        if m.bet == 1
          @double_games_record.push(1)
        end
    end
    return @double_games_record.inject(:+)
  end


  def games_by_night
    @won_25 = false
    @player_games = []
    @wins = [0]
    @last_created_at = matches.first.created_at
    teams.each do |team|
      team.matches.each do |match|
        @player_games.push(match)
      end
    end
    @sorted_player_games = @player_games.sort_by &:created_at
    @sorted_player_games.each do |m|
      if m.created_at > @last_created_at + 12.hours
        @wins = [0]
      end
      @last_created_at = m.created_at
      @teamhome = false
      teams.each do |t|
        if m.teams[0] == t
          @teamhome = true
        end
      end
      if @teamhome
        if m.home > m.away
          @wins.push(1)
        end
      else
        if m.away > m.home
          @wins.push(1)
        end
      end
      if @wins.inject(:+) > 24
        @won_25 = true
      end
    end
    return @won_25
  end

  def gold_night
      @balance_200 = false
      @player_games = []
      @goal_difference = [0]
      @player_games = []
      @balance = []
      @last_created_at = matches.first.created_at
      teams.each do |team|

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
    <div>
      <%= f.label :password, 'Password' %><br>
      <%= f.password_field :password, size: 40 %>
    </div>

    <div>
      <%= f.label :password_confirmation, 'Confirm' %><br>
      <%= f.password_field :password_confirmation, size: 40 %>
    </div>
  <div class="field">
    <%= f.label :mail %><br>
    <%= f.text_field :mail %>
  </div>
  <div class="actions">
    <%= f.submit class: 'button expand' %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path, class: 'button success radius expand' %>

app/views/players/index.html.erb
<h1>Listing players</h1>

<table width="100%">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= link_to player.name, player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Delete', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path, class: 'button success radius expand' %><br>
<%= link_to 'Back', admin_url, class: 'button success radius expand' %>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', statistics_path, class: 'button success radius expand' %>

app/views/players/show.html.erb
<h1><%= @player.name %> - All time</h1>

<table width="100%">
  <thead>
  <tr>
    <th>Spelare:</th>
    <th>GP</th>
    <th>W</th>
    <th>L</th>
    <th>T</th>
    <th>P</th>
    <th>GF</th>
    <th>GA</th>
    <th>Streak</th>
    <th>B</th>
  </tr>
  </thead>
  <tbody>
  <% @all_time_player.each do |player| %>
      <tr>
        <td width="200"><%= link_to "#{player["player"].name}", "players/#{player["player"].id}" %></td>
        <td width="25"><%= player["player_stats"].wins + player["player_stats"].losses + player["player_stats"].ties %></td>
        <td width="25"><%= player["player_stats"].wins %></td>
        <td width="25"><%= player["player_stats"].losses %></td>
        <td width="25"><%= player["player_stats"].ties %></td>
        <td width="25"><%= player["player_stats"].wins * 3 + player["player_stats"].ties %></td>
        <td width="25"><%= player["player_stats"].goals_for %></td>
        <td width="25"><%= player["player_stats"].goals_against %></td>
        <td width="25">
			<% if player["player_stats"].win_streak > 0 %>
			Won <%= player["player_stats"].win_streak %></td> <% end %>
			<% if player["player_stats"].lose_streak > 0 %>
			Lost <%= player["player_stats"].lose_streak %></td> <% end %>
			<% if player["player_stats"].tie_streak > 0 %>
			Tied <%= player["player_stats"].tie_streak %></td> <% end %>
        <td width="25"><%= player["player_stats"].balance %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<h1><%= @player.name %> - Last Season</h1>

<table width="100%">
  <thead>
  <tr>
    <th>Spelare:</th>
    <th>GP</th>
    <th>W</th>
    <th>L</th>
    <th>T</th>
    <th>P</th>
    <th>GF</th>
    <th>GA</th>
    <th>Streak</th>
    <th>B</th>
  </tr>
  </thead>
  <tbody>
  <% @last_season_player.each do |player| %>
      <tr>
        <td width="200"><%= link_to "#{player["player"].name}", "players/#{player["player"].id}" %></td>
        <td width="25"><%= player["player_stats"].wins + player["player_stats"].losses + player["player_stats"].ties %></td>
        <td width="25"><%= player["player_stats"].wins %></td>
        <td width="25"><%= player["player_stats"].losses %></td>
        <td width="25"><%= player["player_stats"].ties %></td>
        <td width="25"><%= player["player_stats"].wins * 3 + player["player_stats"].ties %></td>
        <td width="25"><%= player["player_stats"].goals_for %></td>
        <td width="25"><%= player["player_stats"].goals_against %></td>
        <td width="25">
			<% if player["player_stats"].win_streak > 0 %>
			Won <%= player["player_stats"].win_streak %></td> <% end %>
			<% if player["player_stats"].lose_streak > 0 %>
			Lost <%= player["player_stats"].lose_streak %></td> <% end %>
			<% if player["player_stats"].tie_streak > 0 %>
			Tied <%= player["player_stats"].tie_streak %></td> <% end %>
        <td width="25"><%= player["player_stats"].balance %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<h1><%= @player.name %> - Last Time</h1>

<table width="100%">
  <thead>
  <tr>
    <th>Spelare:</th>
    <th>GP</th>
    <th>W</th>
    <th>L</th>
    <th>T</th>
    <th>P</th>
    <th>GF</th>
    <th>GA</th>
    <th>Streak</th>
    <th>B</th>
  </tr>
  </thead>
  <tbody>
  <% @last_time_player.each do |player| %>
      <tr>
        <td width="200"><%= link_to "#{player["player"].name}", "players/#{player["player"].id}" %></td>
        <td width="25"><%= player["player_stats"].wins + player["player_stats"].losses + player["player_stats"].ties %></td>
        <td width="25"><%= player["player_stats"].wins %></td>
        <td width="25"><%= player["player_stats"].losses %></td>
        <td width="25"><%= player["player_stats"].ties %></td>
        <td width="25"><%= player["player_stats"].wins * 3 + player["player_stats"].ties %></td>
        <td width="25"><%= player["player_stats"].goals_for %></td>
        <td width="25"><%= player["player_stats"].goals_against %></td>
        <td width="25">
			<% if player["player_stats"].win_streak > 0 %>
			Won <%= player["player_stats"].win_streak %></td> <% end %>
			<% if player["player_stats"].lose_streak > 0 %>
			Lost <%= player["player_stats"].lose_streak %></td> <% end %>
			<% if player["player_stats"].tie_streak > 0 %>
			Tied <%= player["player_stats"].tie_streak %></td> <% end %>
        <td width="25"><%= player["player_stats"].balance %></td>
      </tr>
  <% end %>
  </tbody>
</table>


<h3> Walk of Fame</h3>
 <% @achievements.each do |achievement| %>
    <% if achievement[0]["type"] == "fame" %>
        <div class="achievementwrapper">
        <div class="achievementicon"><%=if achievement[1] == 0
                                          image_tag(achievement[0]["img"], size: "32")
                                        else
                                          image_tag("locked.png", size: "32")
                                        end%></div>
        <div class="achievementname"><strong><%= achievement[0]["name"] %></strong><div class="achievementscore"><strong><%= achievement[0]["score"] %>P</strong></div></div>
        <div class="achievementdescription"><%= achievement[0]["description"] %></div>
      </div>
    <% end %>
<% end %>
<h3> Walk of Shame</h3>
<% @achievements.each do |achievement| %>
    <% if achievement[0]["type"] == "shame" %>
        <div class="achievementwrapper">
          <div class="achievementicon"><%=if achievement[1] == 0
                                            image_tag(achievement[0]["img"], size: "32")
                                          else
                                            image_tag("locked.png", size: "32")
                                          end%></div>
          <div class="achievementnameshame"><strong><%= achievement[0]["name"] %></strong><div class="achievementscore"><strong><%= achievement[0]["score"] %>P</strong></div></div>
          <div class="achievementdescription"><%= achievement[0]["description"] %></div>
        </div>
    <% end %>
<% end %>
<br>

<table width="100%">
  <tbody>
      <% @player.sorted_matches.each_with_index do |g, index| %>
          <tr>
            <td width="100"><strong>Match <%= index+1 %></strong></td><td></td>
          </tr>
          <tr>
            <td>Home: <%= g.home %></td>
            <td><strong><%= g.teams[0].name %></strong> (<%= g.teams[0].players.map(&:name).join(', ') %>)</td>
          </tr>
          <tr>
            <td>Away: <%= g.away %></td>
            <td><strong><%= g.teams[1].name %></strong> (<%= g.teams[1].players.map(&:name).join(', ') %>)</td>
          </tr>
      <% end  %>
  </tbody>
</table>
<br>

<%= link_to "Update Achievements", player_achievement_check_path(@player), method: :post, class: 'button success radius expand' %>
<%= link_to 'Edit', edit_player_path(@player), class: 'button success radius expand' %> <br>
<%= link_to 'Back', players_path, class: 'button success radius expand'  %>